'use strict';
(()=>{
 const el=id=>document.getElementById(id),map=window.Bunker;let page='welcome',selected='0',visited=false,portraitAllowed=false,lastFocus=null,noticeTimer=null,registration=null;
 function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
 function guard(){const portrait=matchMedia('(orientation: portrait)').matches&&window.innerWidth<1000;el('portrait-guard').hidden=page==='welcome'||!portrait||portraitAllowed;if(page==='game')map.pause(!el('portrait-guard').hidden||!el('dialog-layer').hidden);}
 function screen(name){page=name;for(const id of['welcome','overview','game'])el(id).hidden=id!==name;map.pause(name!=='game');if(name==='game')map.start();if(name==='overview')el('resume').hidden=!visited;guard();}
 function choose(id){selected=id;const l=VAULT_LEVELS.find(v=>v.id===id);for(const b of el('floors').children)b.setAttribute('aria-pressed',String(b.dataset.level===id));el('floor-number').textContent=l.tech?'ТЕХНИЧЕСКИЙ ПОДУРОВЕНЬ':'УРОВЕНЬ '+Number(l.number);el('floor-title').textContent=l.title;el('floor-description').textContent=l.description;el('floor-locations').replaceChildren(...l.locations.map(text=>{const d=document.createElement('div');d.textContent=text;return d;}));el('floor-orgs').textContent=l.orgs||'';el('floor-state').textContent=l.available?'Доступна прогулка по уровню.':'Подробная карта этого участка ещё готовится.';el('enter-level').disabled=!l.available;el('enter-level').textContent=l.available?'Войти на уровень '+Number(l.number):'Карта появится позже';}
 VAULT_LEVELS.forEach(l=>{const b=document.createElement('button');b.className='floor-row'+(l.tech?' tech':'');b.dataset.level=l.id;b.setAttribute('aria-pressed','false');b.setAttribute('aria-label',(l.tech?'Подуровень '+l.number:'Уровень '+Number(l.number))+': '+l.title);b.innerHTML=`<span class="floor-tag">${l.tech?'':'LVL '}${esc(l.number)}</span><span class="floor-section"><span class="floor-symbol" aria-hidden="true">${esc(l.symbol||'·')}</span><span class="floor-name">${esc(l.title)}</span>${l.available?'<span class="floor-ready">ВХОД</span>':''}</span>`;b.addEventListener('click',()=>choose(l.id));el('floors').append(b);});choose('0');
 el('begin').addEventListener('click',()=>screen('overview'));el('enter-level').addEventListener('click',()=>{if(selected!=='0')return;visited=true;screen('game');});el('resume').addEventListener('click',()=>screen('game'));el('levels').addEventListener('click',()=>{if(map.isBusy())return;screen('overview');});el('allow-portrait').addEventListener('click',()=>{portraitAllowed=true;guard();});window.addEventListener('resize',guard);
 function showDialog(title,html,kind='',kicker='VAULT-TEC / STARFIELD'){lastFocus=document.activeElement;map.pause(true);el('dialog-layer').className='dialog-layer '+kind;el('dialog-title').textContent=title;el('dialog-kicker').textContent=kicker;el('dialog-content').innerHTML=html;el('dialog-layer').hidden=false;el('dialog-close').focus();}
 function closeDialog(){el('dialog-layer').hidden=true;el('dialog-layer').className='dialog-layer';guard();lastFocus?.focus?.();}
 el('dialog-close').addEventListener('click',closeDialog);
 document.addEventListener('keydown',e=>{if(el('dialog-layer').hidden)return;if(e.key==='Escape'){e.preventDefault();closeDialog();return;}if(e.key==='Tab'){const a=[...el('dialog').querySelectorAll('button:not([disabled]),input,a[href]')].filter(n=>n.offsetParent!==null);if(!a.length)return;const i=a.indexOf(document.activeElement);if(e.shiftKey&&i<=0){e.preventDefault();a.at(-1).focus();}else if(!e.shiftKey&&i===a.length-1){e.preventDefault();a[0].focus();}}});
 function welcome(){showDialog('Добро пожаловать!',`<p>В Vault-Tec вас ждали.</p><p>Ваше место в будущем — здесь, в убежище Starfield.</p><p>Для заселения обратитесь к стойке регистрации. После оформления следуйте к пассажирскому лифту.</p><p class="small">VAULT-TEC INDUSTRIES · СИСТЕМА ПРИЁМА ЖИТЕЛЕЙ</p><button data-do="close">Продолжить</button>`);}
 function register(){showDialog('Регистрация прибывшего',`<p>Укажите количество крышек для определения класса спальни.</p><form id="caps-form"><label for="caps">Количество крышек</label><input id="caps" name="caps" inputmode="numeric" type="number" min="0" max="999999999" step="1" value="${registration?.caps||300}" required><div class="choices"><button type="button" data-caps="300">300</button><button type="button" data-caps="1000">1000</button><button type="button" data-caps="1500">1500+</button></div><button class="primary" type="submit">Получить назначение</button></form><div id="registration-result" role="status"></div><p class="small">Сумма указывается вручную. Баланс персонажа не изменяется.</p>`,'','STARFIELD / СЛУЖБА ЗАСЕЛЕНИЯ');el('caps-form').addEventListener('submit',e=>{e.preventDefault();const raw=el('caps').value,n=Number(raw),out=el('registration-result');if(raw.trim()===''||!Number.isSafeInteger(n)||n<0||n>999999999){out.className='result';out.textContent='Введите целое неотрицательное число.';return;}out.className='result';if(n<300){out.textContent='Недостаточно средств для заселения. Минимальная сумма — 300 крышек.';return;}const grade=n>=1500?'ЛЮКС':n>=1000?'УЛУЧШЕННАЯ СПАЛЬНЯ':'ОБЫЧНАЯ СПАЛЬНЯ';registration={caps:n,grade};out.innerHTML=`НАЗНАЧЕНИЕ ПОДТВЕРЖДЕНО<br><strong>${grade}</strong><br>Жилой сектор · уровень 1<br><span class="small">Подробная карта жилого уровня готовится.</span>`;});}
 function terminal(){showDialog('Главный терминал',`<div class="terminal-menu"><button data-do="welcome">01 / Приветствие Vault-Tec</button><button data-do="overview">02 / Структура убежища</button><button data-do="rules">03 / Правила и допуски</button><button data-do="notices">04 / Системные сообщения</button><button data-do="assignment">05 / Назначение спальни</button></div>`);}
 function denied(){showDialog('НЕТ ДОСТУПА',`<p>Выход на Поверхность заблокирован.</p><p>Ваш допуск не разрешает открытие внешнего контура.</p><p class="small">РАЗРЕШЕНИЕ: СПЕЦИАЛИЗИРОВАННЫЕ РОБОТЫ ОБСЛУЖИВАНИЯ</p><button data-do="close">Вернуться в убежище</button>`,'denied','ОТКАЗ В ДОСТУПЕ / ВНЕШНИЙ КОНТУР');}
 function notices(){showDialog('Системные сообщения',`<p>Регистрация прибывших осуществляется в центральном фойе.</p><p>Проход из входного шлюза — через дезактивационную камеру и контроль допуска.</p><p>Пассажирские лифты обслуживают основные этажи. Доступ к техническим подуровням осуществляется служебными маршрутами.</p><p class="small">Сообщения автономной системы убежища.</p>`);}
 function organizations(){showDialog('Организации Starfield',`<div class="org-list">${VAULT_ORGS.map(o=>`<article><small>${esc(o[0])==='ТЕХ'?'ТЕХНИЧЕСКИЕ ПЕРЕХОДЫ':'УРОВЕНЬ / ПЕРЕХОД '+esc(o[0])}</small><strong>${esc(o[1])}</strong><p>${esc(o[2])}</p></article>`).join('')}</div><p class="small">На нулевом уровне представительства организаций не отмечены.</p>`);}
 function floorPlan(){showDialog('Уровень 0 · Схема',`<canvas id="plan-map" class="plan-canvas" aria-label="Схема круглого фойе с лифтом в центре, регистрацией, шлюзом и выходом"></canvas><div class="route-list"><button data-route="registration">Регистрация</button><button data-route="mainTerminal">Терминал</button><button data-route="entry">Дезактивация</button><button data-route="exit">Выход</button><button data-route="lift">Лифты</button></div><p class="small">Нажмите название, чтобы проложить путь. Из отдельного блока сначала вернитесь в фойе.</p>`);map.renderPlan(el('plan-map'));}
 function action(name){switch(name){case'welcome':welcome();break;case'registration':register();break;case'terminal':terminal();break;case'denied':denied();break;case'notices':notices();break;case'levels':screen('overview');break;case'robot':showDialog('Робот-контроллер',`<p>Прибывший, следуйте внутреннему маршруту. Оформление заселения — у стойки регистрации в фойе.</p><div class="terminal-menu"><button data-do="plan">Где находится регистрация?</button><button data-do="rules">Какие зоны доступны?</button><button data-do="overview">Показать уровни убежища</button></div>`);break;case'scan':showDialog('Контроль доступа',`<p>Идентификация посетителя завершена.</p><div class="result">ДОСТУП: ЦЕНТРАЛЬНОЕ ФОЙЕ<br>ВНЕШНИЙ КОНТУР: ЗАКРЫТ</div><p>Для назначения жилого помещения пройдите регистрацию.</p>`);break;case'airlock':showDialog('Входной шлюз',`<p>Внешние и внутренние ворота открываются поэтапно. Перед проходом в убежище требуется санитарная обработка.</p><p>Не задерживайтесь в дверных проёмах.</p>`);break;case'surfaceInfo':showDialog('Выход на Поверхность',`<p>Маршрут изолирован от основной части убежища.</p><p>Особый допуск на открытие внешнего контура предоставлен только некоторым роботам обслуживания.</p><button data-do="denied">Запросить доступ</button>`);break;case'residential':showDialog('Жилые секции',`<p>Спальные блоки находятся на уровне 1. Пассажирские лифты расположены в центре фойе.</p>${registration?`<div class="result">Ваше назначение: <strong>${esc(registration.grade)}</strong></div>`:'<p>Назначение спальни выдаётся у стойки регистрации.</p>'}<button data-do="overview">Открыть схему этажей</button>`);break;case'freight':showDialog('Служебные маршруты',`<p>Грузовые лифты и сервисные проходы обслуживают инженерные зоны комплекса.</p><p>Технические подуровни не имеют остановок пассажирских лифтов.</p><button data-do="overview">Посмотреть подуровни</button>`);break;}}
 el('dialog-content').addEventListener('click',e=>{const caps=e.target.closest('[data-caps]');if(caps){el('caps').value=caps.dataset.caps;return;}const route=e.target.closest('[data-route]');if(route){closeDialog();map.route(route.dataset.route);return;}const b=e.target.closest('[data-do]');if(!b)return;const name=b.dataset.do;if(name==='close')closeDialog();else if(name==='overview'){closeDialog();screen('overview');}else if(name==='plan')floorPlan();else if(name==='rules')showDialog('Правила и допуски',`<p>Убежищем управляет автономная роботизированная система. Смотрителя нет.</p><p>Соблюдайте указания контроллеров и статус дверных индикаторов. Красный — закрыто; зелёный — проход открыт.</p><p>Выход на Поверхность и служебные зоны требуют отдельного допуска.</p>`);else if(name==='assignment')showDialog('Назначение спальни',registration?`<div class="result">${esc(registration.grade)}<br>Жилой сектор · уровень 1</div><p>Подробная карта жилого уровня готовится.</p>`:'<p>Назначение ещё не оформлено. Обратитесь к стойке регистрации.</p>');else action(name);});
 el('overview-orgs').addEventListener('click',organizations);el('floor-plan').addEventListener('click',()=>{if(!map.isBusy())floorPlan();});el('help').addEventListener('click',()=>{if(map.isBusy())return;showDialog('Управление',`<p><strong>Идти:</strong> нажмите на свободный пол или используйте стрелки. На компьютере — WASD.</p><p><strong>Взаимодействовать:</strong> нажмите на объект, подойдите и используйте кнопку действия. На клавиатуре — E.</p><p><strong>Осмотреться:</strong> потяните карту. Кнопка ◎ возвращает камеру к персонажу, + и − меняют масштаб.</p><p><strong>Другой этаж:</strong> кнопка «Этажи» открывает общий разрез убежища.</p>`);});
 el('center').addEventListener('click',()=>map.center());el('zoom-in').addEventListener('click',()=>map.zoom(.25));el('zoom-out').addEventListener('click',()=>map.zoom(-.25));el('action').addEventListener('click',()=>map.act());
 map.onAction=action;map.onScene=label=>el('place').textContent=label;map.onTarget=({label,target,disabled})=>{if(el('action').textContent!==label)el('action').textContent=label;el('action').disabled=disabled;el('target-label').textContent=target;el('target-label').hidden=!target;};map.onNotice=text=>{clearTimeout(noticeTimer);el('status').textContent=text;if(text)noticeTimer=setTimeout(()=>el('status').textContent='',4800);};map.onProcess=({active,progress,label})=>{el('processing').hidden=!active;if(active){el('process-label').textContent=label;el('process-progress').value=progress;}};
 map.ready.then(()=>{el('begin').disabled=false;el('begin').textContent='Далее · схема убежища';}).catch(e=>{el('begin').textContent='Перезагрузить';el('begin').disabled=false;el('begin').onclick=()=>location.reload();el('load-error').hidden=false;el('load-error').textContent='Не удалось загрузить карту. Проверьте соединение и повторите.';console.error(e);});
})();
