'use strict';
window.Bunker=(()=>{
 const canvas=document.getElementById('world');let ctx=canvas.getContext('2d',{alpha:false});
 const images={},darkImages={},keys=new Set(),surfaceTextures={},wallCaches=new Map();
 const CONTAINER_SPRITES=['box','supplyCase','uniformCrate','luggageCabinet'],CONTAINER_DURATION=.72;
 let W=1000,H=650,dpr=1,dirty=true,last=0,ready=false,running=false,paused=false,time=0,pointer=null,currentZone='';
 const state={scene:'foyer',zoom:1,cam:{x:20,y:44.5},follow:true,path:[],selected:null,near:null,open:{},anim:{},cleaned:{A:false,B:false},cycle:null,transition:null,goal:null,closers:{},characterClass:null,accessApproved:false,container:null};
 const CLASS_NAMES={raider:'Райдер',resident:'Житель',ghoul:'Гуль'};
 try{const saved=window.sessionStorage?.getItem('starfield-character-class');if(Object.hasOwn(CLASS_NAMES,saved))state.characterClass=saved;}catch{}
 const player={x:20.5,y:45.5,angle:0,facing:2,phase:0,moving:false};
 const level=createLevelZero(),scenes={foyer:level};
 const WALL_HEIGHT=2.45,WALL_THICKNESS=.12,DOOR_DURATION=.85,key=(x,y)=>Math.floor(x)+','+Math.floor(y);
 function inside(x,y,poly){let yes=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[i],b=poly[j];if((a[1]>y)!==(b[1]>y)&&x<(b[0]-a[0])*(y-a[1])/(b[1]-a[1])+a[0])yes=!yes;}return yes;}
 function onFloor(x,y){return level.shapes.some(p=>inside(x,y,p));}
 for(let y=0;y<level.h;y++)for(let x=0;x<level.w;x++)if(onFloor(x+.5,y+.5))level.tiles.add(key(x,y));
 function current(){return level;}
 function project(x,y,z=0){return[W/2+(x-y-state.cam.x+state.cam.y)*38*state.zoom,H*.53+(x+y-state.cam.x-state.cam.y)*19*state.zoom-z*42*state.zoom];}
 function inverse(x,y){const a=(x-W/2)/(38*state.zoom)+state.cam.x-state.cam.y,b=(y-H*.53)/(19*state.zoom)+state.cam.x+state.cam.y;return{x:(a+b)/2,y:(b-a)/2};}
 function polygon(verts,fill,stroke){ctx.beginPath();verts.forEach((v,i)=>i?ctx.lineTo(...project(...v)):ctx.moveTo(...project(...v)));ctx.closePath();if(fill){ctx.fillStyle=fill;ctx.fill();}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=Math.max(.65,state.zoom);ctx.stroke();}}
 function textureQuad(image,vertices,crop=null){const p=vertices.map(v=>project(...v)),w=crop?crop[2]:image.width,h=crop?crop[3]:image.height;ctx.save();ctx.beginPath();p.forEach((v,i)=>i?ctx.lineTo(...v):ctx.moveTo(...v));ctx.closePath();ctx.clip();ctx.transform((p[1][0]-p[0][0])/w,(p[1][1]-p[0][1])/w,(p[3][0]-p[0][0])/h,(p[3][1]-p[0][1])/h,p[0][0],p[0][1]);if(crop)ctx.drawImage(image,...crop,0,0,w,h);else ctx.drawImage(image,0,0);ctx.restore();}
 function faceTexture(image,p0,p1,p3,w,h){const source=document.createElement('canvas');source.width=image.width;source.height=image.height;const s=source.getContext('2d');s.drawImage(image,0,0);const px=s.getImageData(0,0,source.width,source.height).data;const c=document.createElement('canvas');c.width=w;c.height=h;const g=c.getContext('2d'),d=g.createImageData(w,h);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const u=(x+.5)/w,v=(y+.5)/h,sx=Math.max(0,Math.min(source.width-1,Math.floor(p0[0]+u*(p1[0]-p0[0])+v*(p3[0]-p0[0])))),sy=Math.max(0,Math.min(source.height-1,Math.floor(p0[1]+u*(p1[1]-p0[1])+v*(p3[1]-p0[1])))),i=(sy*source.width+sx)*4,j=(y*w+x)*4;for(let k=0;k<3;k++)d.data[j+k]=px[i+3]?px[i+k]:[67,78,72][k];d.data[j+3]=255;}g.putImageData(d,0,0);return c;}
 function buildSurfaces(){
  surfaceTextures.floor=faceTexture(images.floor,[37,1],[73,19],[1,19],64,64);
  surfaceTextures.grate=faceTexture(images.grate,[37,1],[73,19],[1,19],64,64);
  surfaceTextures.wall=faceTexture(darkImages.wallA,[2,12],[36,29],[2,96],40,100);
  surfaceTextures.detail=faceTexture(darkImages.wallDetailA,[2,12],[37,29],[2,96],40,100);
  surfaceTextures.door=faceTexture(darkImages.door,[48,64],[105,50],[48,126],64,96);
  for(const name of['stripLight','welcomePoster','noticePanel','entryPanel','surfaceDisplay','systemsPanel','communityPoster','receptionClock'])surfaceTextures[name]=images[name];
  const vent=document.createElement('canvas');vent.width=56;vent.height=36;const vg=vent.getContext('2d');vg.imageSmoothingEnabled=false;vg.drawImage(surfaceTextures.wall,0,0,56,36);vg.fillStyle='#26362f';vg.fillRect(3,3,50,30);vg.drawImage(surfaceTextures.grate,0,0,64,64,6,6,44,24);vg.strokeStyle='#788378';vg.strokeRect(.5,.5,55,35);for(const x of[3,52])for(const y of[3,32]){vg.fillStyle='#a3aaa0';vg.fillRect(x,y,1,1);}surfaceTextures.vaultVent=vent;
  const glow=document.createElement('canvas');glow.width=64;glow.height=96;const g=glow.getContext('2d'),grad=g.createRadialGradient(32,22,2,32,30,58);grad.addColorStop(0,'#fff0bc75');grad.addColorStop(.4,'#ead8a330');grad.addColorStop(1,'#ead8a300');g.fillStyle=grad;g.fillRect(0,0,64,96);surfaceTextures.lampGlow=glow;
 }
 function wallPoint(o,u,z,n=0){const nx=-o.uy,ny=o.ux;return[o.x+o.ux*u+nx*n,o.y+o.uy*u+ny*n,z];}
 function wallFace(o,a,b,z0,z1,n=0){return[wallPoint(o,a,z1,n),wallPoint(o,b,z1,n),wallPoint(o,b,z0,n),wallPoint(o,a,z0,n)];}
 function wallPanel(o,a,b,z0,z1,texture='wall'){const t=WALL_THICKNESS;textureQuad(surfaceTextures[texture],wallFace(o,a,b,z0,z1));polygon([wallPoint(o,b,z0,-t),wallPoint(o,b,z0),wallPoint(o,b,z1),wallPoint(o,b,z1,-t)],'#3d4943');polygon([wallPoint(o,a,z1,-t),wallPoint(o,b,z1,-t),wallPoint(o,b,z1),wallPoint(o,a,z1)],'#768174','#8b9683');polygon(wallFace(o,a,b,.025,.12,.003),'#313c35');}
 function wallDraw(o){const detail=Math.floor(o.x+o.y)%5===0,cacheKey=[o.ux.toFixed(4),o.uy.toFixed(4),o.span.toFixed(4),o.low,detail].join('/');let im=wallCaches.get(cacheKey);if(!im){const saved={W,H,ctx,cam:state.cam,zoom:state.zoom};im=document.createElement('canvas');im.width=160;im.height=170;ctx=im.getContext('2d');ctx.imageSmoothingEnabled=false;W=160;H=170;state.cam={x:-1.05263,y:-1.05263};state.zoom=1;wallPanel({...o,x:0,y:0},0,o.span,0,WALL_HEIGHT,detail?'detail':'wall');W=saved.W;H=saved.H;ctx=saved.ctx;state.cam=saved.cam;state.zoom=saved.zoom;wallCaches.set(cacheKey,im);}const p=project(o.x,o.y),z=state.zoom;ctx.save();if(o.low)ctx.globalAlpha=.5;ctx.drawImage(im,Math.round(p[0]-80*z),Math.round(p[1]-130.1*z),Math.round(160*z),Math.round(170*z));ctx.restore();if(o.low)wallPanel(o,0,o.span,0,.3);for(const fitting of o.fittings||[])fixtureDraw(fitting,o);}
 function fixtureDraw(o,panel){
  const im=surfaceTextures[o.sprite],direction=o.ux-o.uy<0?-1:1,ux=o.ux*direction,uy=o.uy*direction;
  const wall={x:o.x-ux*o.width/2,y:o.y-uy*o.width/2,ux,uy},height=o.height;
  ctx.save();if(o.low)ctx.globalAlpha=.5;
  // Each supporting panel draws its slice. Wide plaques cannot float or hide behind seams.
  if(panel){const clip=wallFace(panel,0,panel.span,0,WALL_HEIGHT).map(v=>project(...v));ctx.beginPath();clip.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.closePath();ctx.clip();}
  if(o.sprite==='stripLight'){
   const wash={x:o.x-ux*.46,y:o.y-uy*.46,ux,uy};textureQuad(surfaceTextures.lampGlow,wallFace(wash,0,.92,.4,2.43,.012));
  }
  textureQuad(im,wallFace(wall,0,o.width,o.z-height/2,o.z+height/2,.014));ctx.restore();
 }
 function doorWorld(o,u=.5,z=0,n=0){return wallPoint(o,u*o.span,z,n);}
 function doorClear(o){return !!state.open[o.id]&&(state.anim[o.id]||0)>=.96;}
 function doorMoving(o){return Math.abs((state.anim[o.id]||0)-(state.open[o.id]?1:0))>.001;}
 function segmentDistance(x,y,o){const u=(x-o.x)*o.ux+(y-o.y)*o.uy,t=Math.max(0,Math.min(o.span,u));return Math.hypot(x-o.x-o.ux*t,y-o.y-o.uy*t);}
 function doorOccupied(o){return segmentDistance(player.x,player.y,o)<.48;}
 function doorDraw(o){const span=o.span,edge=.12,h=2.12,p=state.anim[o.id]||0,ease=p*p*(3-2*p),q=(span-2*edge)/2;
  polygon([wallPoint(o,0,0,-.13),wallPoint(o,span,0,-.13),wallPoint(o,span,.015,.13),wallPoint(o,0,.015,.13)],'#697569','#a09567');
  if(o.action)polygon(wallFace(o,edge,span-edge,.02,h,-.05),'#111815');
  const opening=wallFace(o,edge,span-edge,.025,h,-.02).map(v=>project(...v));ctx.save();ctx.beginPath();opening.forEach((v,i)=>i?ctx.lineTo(...v):ctx.moveTo(...v));ctx.closePath();ctx.clip();
  textureQuad(surfaceTextures.door,wallFace(o,edge-q*ease,edge+q-q*ease,.025,h,-.02),[0,0,32,96]);textureQuad(surfaceTextures.door,wallFace(o,edge+q+q*ease,span-edge+q*ease,.025,h,-.02),[32,0,32,96]);ctx.restore();
  wallPanel(o,0,edge,0,h);wallPanel(o,span-edge,span,0,h);wallPanel(o,0,span,h,WALL_HEIGHT);
  for(const u of[edge,span-edge]){const a=project(...wallPoint(o,u,.03,.007)),b=project(...wallPoint(o,u,h,.007));ctx.beginPath();ctx.moveTo(...a);ctx.lineTo(...b);ctx.strokeStyle='#172b25';ctx.lineWidth=2*state.zoom;ctx.stroke();}
  polygon(wallFace(o,span*.43,span*.57,2.22,2.31,.016),doorClear(o)?'#9fc783':doorMoving(o)?'#c4ac62':'#ba6750');
  if(o.blast){const p=project(...doorWorld(o,.5,1.08));ctx.save();ctx.translate(...p);ctx.scale(1,.9);ctx.strokeStyle='#b0a174';ctx.lineWidth=3*state.zoom;ctx.beginPath();ctx.ellipse(0,0,23*state.zoom,33*state.zoom,-.43,0,7);ctx.stroke();ctx.restore();}
 }
 function crosses(x,y,ex,ey,o){const ax=ex-x,ay=ey-y,bx=o.ux*o.span,by=o.uy*o.span,den=ax*by-ay*bx;if(Math.abs(den)<.000001)return false;const u=((o.x-x)*by-(o.y-y)*bx)/den,v=((o.x-x)*ay-(o.y-y)*ax)/den;return u>0&&u<=1&&v>=-.01&&v<=1.01;}
 function pass(x,y,ignoreDoors=false){if(!onFloor(x,y)||level.blocked.has(key(x,y)))return false;for(const wall of level.walls)if(segmentDistance(x,y,wall)<.13)return false;if(!ignoreDoors)for(const d of level.doors)if(!doorClear(d)&&segmentDistance(x,y,d)<.18)return false;return true;}
 function canStep(x,y,ex,ey,ignoreDoors=false){if(!pass(ex,ey,ignoreDoors))return false;for(const w of level.walls)if(crosses(x,y,ex,ey,w))return false;for(const d of level.doors)if((d.action||(!ignoreDoors&&!doorClear(d)))&&crosses(x,y,ex,ey,d))return false;return true;}
 function pathTo(tx,ty,ignoreDoors=false){const sx=Math.floor(player.x),sy=Math.floor(player.y),ex=Math.floor(tx),ey=Math.floor(ty);if(!pass(ex+.5,ey+.5,ignoreDoors))return null;const queue=[[sx,sy]],parents=new Map([[key(sx,sy),null]]);for(let i=0;i<queue.length;i++){const [x,y]=queue[i];if(x===ex&&y===ey){const result=[];let p=[x,y];while(p){result.unshift({x:p[0]+.5,y:p[1]+.5});p=parents.get(key(...p));}result.shift();return result;}for(const[dx,dy]of[[1,0],[-1,0],[0,1],[0,-1]]){const a=x+dx,b=y+dy,k=key(a,b);if(!parents.has(k)&&canStep(x+.5,y+.5,a+.5,b+.5,ignoreDoors)){parents.set(k,[x,y]);queue.push([a,b]);}}}return null;}
 function interactables(){return [...level.doors,...level.objects.filter(o=>o.action)];}
 function distance(o){if(o.internal)return segmentDistance(player.x,player.y,o);const a=o.approach||[o.x,o.y];return Math.hypot(player.x-a[0],player.y-a[1]);}
 function say(s){api.onNotice?.(s);}
 function nearObject(){let best=null,d=1.65;for(const o of interactables()){const n=distance(o);if(n<d){best=o;d=n;}}return best;}
 function updateAction(){const o=state.selected&&distance(state.selected)<1.7?state.selected:nearObject();state.near=o;let label=o?.label||'Подойдите к объекту';const busy=!!state.cycle||containerBusy()||(o?.door&&doorMoving(o));if(containerBusy())label=state.container.phase==='opening'?'Крышка открывается…':'Крышка закрывается…';else if(state.cycle)label='Идёт обработка…';else if(o?.door&&doorMoving(o))label=state.open[o.id]?'Дверь открывается…':'Дверь закрывается…';else if(o?.internal&&state.open[o.id])label='Закрыть дверь';api.onTarget?.({label,target:o?.target||'',disabled:!o||busy});const zone=zoneAt(player.x,player.y);if(zone!==currentZone){currentZone=zone;api.onScene?.(zone);}}
 function approaches(o){if(o.internal){const points=[];for(let u=.5;u<o.span;u++)for(const n of[-.5,.5])points.push(o.axis==='x'?[o.x+u,o.y+n]:[o.x+n,o.y+u]);return points;}return o.approach?[o.approach]:[[o.x+.5,o.y+.5]];}
 function request(o,guided=false){if(!o||state.cycle||state.container)return;if(!guided)state.goal=null;state.selected=o;let best=null;for(const c of approaches(o)){const route=pathTo(...c);if(route&&(!best||route.length<best.length))best=route;}
  if(best){state.path=best;say(best.length?'Подойдите и нажмите кнопку действия.':'');}
  else if(distance(o)<1.7)state.path=[];
  else {const destination=o.approach||approaches(o)[0],route=pathTo(...destination,true);let found=null;if(route){let prev={x:player.x,y:player.y};for(const p of route){found=level.doors.find(d=>d.internal&&!doorClear(d)&&crosses(prev.x,prev.y,p.x,p.y,d));if(found)break;prev=p;}}
   if(found){state.goal=o.id;request(found,true);say('По пути — закрытый шлюз. Подойдите к двери и откройте её.');}else say('Проход занят. Выберите свободный подход.');}
  updateAction();dirty=true;
 }
 function setDoor(o,open){if(!!state.open[o.id]!==open)api.onSound?.(open?'door-open':'door-close');state.open[o.id]=open;if(open)state.closers[o.id]={crossed:false,clearFor:0,age:0};else delete state.closers[o.id];dirty=true;}
 function atCheckpoint(){return [level.doors.find(o=>o.id==='accessGate'),...level.objects.filter(o=>['scanner','robot'].includes(o.id))].some(o=>o&&distance(o)<1.7);}
 function requestPass(){if(!Object.values(state.cleaned).some(Boolean)){say('Сначала пройдите санитарную обработку.');return false;}if(!atCheckpoint()){say('Подойдите к роботу или терминалу контроля доступа.');return false;}api.onAction?.('scan');return true;}
 function confirmClass(value){if(!Object.hasOwn(CLASS_NAMES,value)||!atCheckpoint()||!Object.values(state.cleaned).some(Boolean)||state.cycle)return false;state.characterClass=value;state.accessApproved=true;try{window.sessionStorage?.setItem('starfield-character-class',value);}catch{}setDoor(level.doors.find(o=>o.id==='accessGate'),true);api.onPass?.(getPass());return true;}
 function getPass(){return{characterClass:state.characterClass,label:CLASS_NAMES[state.characterClass]||null,approved:state.accessApproved,clean:Object.values(state.cleaned).some(Boolean)};}
 function act(){const o=state.near;if(!o||distance(o)>1.7||state.cycle||state.container)return;state.path=[];keys.clear();player.moving=false;
  if(o.internal){if(doorMoving(o))return;if(state.open[o.id]&&doorOccupied(o)){say('Отойдите от дверного проёма.');return;}
   if(!state.open[o.id]&&o.requiresClean&&!state.cleaned[o.chamber]){say('Сначала запустите обработку на терминале внутри камеры.');return;}
   if(!state.open[o.id]&&o.checkpoint&&!state.accessApproved){requestPass();return;}
   setDoor(o,!state.open[o.id]);say(state.open[o.id]?'Дверь открывается. После прохода она закроется автоматически.':'Дверь закрывается.');
  }else if(o.action==='container'){if(CONTAINER_SPRITES.includes(o.sprite)){api.onSound?.('box-open');state.container={id:o.id,phase:'opening',t:0};state.goal=null;}else api.onAction?.('container',o.inventory||o.id);}
  else if(o.action==='decon')startDecon(o.chamber);
  else if(o.action==='scan')requestPass();
  else api.onAction?.(o.action);dirty=true;updateAction();
 }
 function containerBusy(){return !!state.container&&state.container.phase!=='held';}
 function closeContainer(){if(!state.container||state.container.phase==='closing')return;api.onSound?.('box-close');state.container.phase='closing';state.container.t=0;keys.clear();dirty=true;}
 function animateContainer(dt){const c=state.container;if(!c||c.phase==='held')return;c.t+=dt;dirty=true;if(c.phase==='opening'&&c.t>=CONTAINER_DURATION+.18){const o=level.objects.find(o=>o.id===c.id);c.phase='held';state.open[c.id]=true;api.onAction?.('container',o.inventory||o.id);}else if(c.phase==='closing'&&c.t>=CONTAINER_DURATION){state.open[c.id]=false;state.container=null;keys.clear();}}
 function autoClose(dt){for(const o of level.doors.filter(o=>o.internal)){if(!state.open[o.id]){delete state.closers[o.id];continue;}if(state.cycle&&o.chamber===state.cycle.lane)continue;const t=state.closers[o.id]||(state.closers[o.id]={crossed:false,clearFor:0,age:0});if(!doorClear(o))continue;t.age+=dt;const clear=segmentDistance(player.x,player.y,o)>.8;if(t.crossed&&clear)t.clearFor+=dt;else t.clearFor=0;if((t.clearFor>.85||(t.age>10&&segmentDistance(player.x,player.y,o)>2))&&!doorOccupied(o))setDoor(o,false);}}
 function startDecon(lane){const b=level.chambers[lane];if(!b||player.x<b.x||player.x>b.x+b.w||player.y<b.y+.4||player.y>b.y+b.h-.4){say('Войдите внутрь камеры и подойдите к её терминалу.');return;}state.cycle={lane,t:0,phase:'closing'};for(const side of['Inner','Outer'])state.open['clean'+side+lane]=false;state.path=[];keys.clear();api.onProcess?.({active:true,progress:0,label:'Герметизация камеры '+lane});}
 function animate(dt){autoClose(dt);animateContainer(dt);for(const o of level.doors){if(o.internal&&!state.open[o.id]&&(state.anim[o.id]||0)>0&&doorOccupied(o))setDoor(o,true);const target=state.open[o.id]?1:0,a=state.anim[o.id]||0;if(Math.abs(a-target)>.0001){const step=dt/DOOR_DURATION;state.anim[o.id]=target>a?Math.min(target,a+step):Math.max(target,a-step);dirty=true;}}
  const c=state.cycle;if(c){dirty=true;const inner='cleanInner'+c.lane,outer='cleanOuter'+c.lane;
   if(c.phase==='closing'){if((state.anim[inner]||0)===0&&(state.anim[outer]||0)===0){c.phase='steam';c.t=0;api.onSound?.('steam');}}
   else if(c.phase==='steam'){c.t+=dt;api.onProcess?.({active:true,progress:Math.min(1,c.t/4.8),label:c.t<3.5?'Дезактивация · камера '+c.lane:'Проверка…'});if(c.t>=4.8){api.onSound?.('steam-stop');api.onSound?.('confirm');c.phase='opening';state.cleaned[c.lane]=true;setDoor(level.doors.find(o=>o.id===inner),true);api.onProcess?.({active:true,progress:1,label:'Обработка завершена'});}}
   else if(c.phase==='opening'&&(state.anim[inner]||0)>=1){state.cycle=null;api.onProcess?.({active:false});say('Обработка завершена. Следуйте к контролю доступа.');}
  }
  if(!state.cycle&&state.goal&&state.selected?.door&&doorClear(state.selected)&&!state.path.length){const goal=interactables().find(o=>o.id===state.goal);state.goal=null;if(goal)request(goal);}
 }
 function move(dx,dy,dt){const len=Math.hypot(dx,dy);if(len<.001)return false;const step=Math.min(3.8*dt,len),nx=player.x+dx/len*step,ny=player.y+dy/len*step;if(canStep(player.x,player.y,nx,ny)){for(const o of level.doors)if(o.internal&&doorClear(o)&&crosses(player.x,player.y,nx,ny,o)){const t=state.closers[o.id]||(state.closers[o.id]={crossed:false,clearFor:0,age:0});t.crossed=true;t.clearFor=0;}player.x=nx;player.y=ny;player.angle=Math.atan2(dy,dx);player.facing=actorDirection(dx,dy);player.phase+=step*2.25;return true;}return false;}
 function zoneAt(x,y){if(y>=42)return'Вход из системы бункеров';if(y>=36&&x>=16&&x<=24)return'Дезактивационные камеры';if(y>=30&&x>=16&&x<=24)return'Контроль доступа';if(x>=32)return'Шлюз на Поверхность';if(x<8)return'Лестничный переход · жилой сектор';for(const z of level.zones)if(x>=z.x&&x<z.x+z.w&&y>=z.y&&y<z.y+z.h)return z.name;return'Центральное фойе';}
 function drawSprite(name,x,y,scale=1,anchor=.5,flip=false,z=0,foot=1){const image=images[name],p=project(x,y,z);if(!image)return;const w=image.width*scale*state.zoom,h=image.height*scale*state.zoom;if(p[0]+w<0||p[0]-w>W||p[1]<0||p[1]-h>H)return;ctx.save();if(flip){ctx.translate(Math.round(p[0]),0);ctx.scale(-1,1);ctx.drawImage(image,Math.round(-w*anchor),Math.round(p[1]-h*foot),Math.round(w),Math.round(h));}else ctx.drawImage(image,Math.round(p[0]-w*anchor),Math.round(p[1]-h*foot),Math.round(w),Math.round(h));ctx.restore();}
 function containerDraw(o){
  const c=state.container?.id===o.id?state.container:null,p=c?c.phase==='held'?1:c.phase==='closing'?1-Math.min(1,c.t/CONTAINER_DURATION):Math.min(1,c.t/CONTAINER_DURATION):state.open[o.id]?1:0;
  if(!p){drawSprite(o.sprite,o.x,o.y,o.scale,.5,o.flip,o.z||0,o.foot||1);return;}
  const base=images[o.sprite],im=images[o.sprite+'Opening'],w=base.width+24,h=base.height+32,z=o.scale*state.zoom,at=project(o.x,o.y,o.z||0),frame=Math.min(9,Math.round(p*9));
  ctx.save();ctx.translate(Math.round(at[0]),Math.round(at[1]));if(o.flip)ctx.scale(-1,1);ctx.drawImage(im,frame*w,0,w,h,Math.round(-(base.width/2+12)*z),Math.round(-(base.height*(o.foot||1)+28)*z),Math.round(w*z),Math.round(h*z));ctx.restore();
 }
 function tileVertices(x,y,z=0){return[[x,y,z],[x+1,y,z],[x+1,y+1,z],[x,y+1,z]];}
 function paintStrip(x,y,w,h,color='#a99b6877'){polygon([[x,y,.02],[x+w,y,.02],[x+w,y+h,.02],[x,y+h,.02]],color);}
 function floorCircle(){for(const r of[2.7,3]){const v=Array.from({length:64},(_,i)=>{const a=i/64*Math.PI*2;return[20+Math.cos(a)*r,19+Math.sin(a)*r,.02];});polygon(v,null,'#a99c69');}for(let i=0;i<12;i++){const a=i/12*Math.PI*2;paintStrip(20+Math.cos(a)*2.82-.055,19+Math.sin(a)*2.82-.055,.11,.11,'#c3b27e');}const p=project(20,19,.025);ctx.save();ctx.translate(...p);ctx.scale(1,.5);ctx.textAlign='center';ctx.font='bold 15px monospace';ctx.fillStyle='#b6ad83';ctx.fillText('ЛИФТОВАЯ ШАХТА',0,-4);ctx.font='12px monospace';ctx.fillText('УРОВЕНЬ 1',0,17);ctx.restore();}
 function floorAccents(){floorCircle();for(const y of[16.5,21.5])paintStrip(9,y,22,.055,'#aa996344');for(const x of[16.5,23.4])paintStrip(x,31,.06,16);for(const b of Object.values(level.chambers))for(let y=37;y<41;y++)for(let x=Math.ceil(b.x);x<b.x+b.w;x++)textureQuad(surfaceTextures.grate,tileVertices(x,y,.02));for(const y of[35.8,41.8,31.8])for(let x=16.2;x<24;x+=.55)paintStrip(x,y,.3,.11,'#b7a45c');
  for(const lamp of level.objects.filter(o=>o.sprite==='stripLight')){
   let nx=-lamp.uy,ny=lamp.ux;if(!onFloor(lamp.x+nx*.5,lamp.y+ny*.5)){nx=-nx;ny=-ny;}
   const p=project(lamp.x+nx*.85,lamp.y+ny*.85,.018);ctx.save();ctx.translate(...p);ctx.scale(1,.5);const glow=ctx.createRadialGradient(0,0,0,0,0,62);glow.addColorStop(0,'#ead6a336');glow.addColorStop(.4,'#dfd2a71c');glow.addColorStop(1,'#dfd2a700');ctx.fillStyle=glow;ctx.fillRect(-62,-62,124,124);ctx.restore();
  }
  for(const o of level.objects){if(!o.sprite||o.mount)continue;const p=project(o.x,o.y,.01),z=state.zoom;ctx.save();ctx.translate(...p);ctx.scale(1,.48);ctx.fillStyle='#080f1059';ctx.beginPath();ctx.ellipse(-3,0,20*o.scale,12*o.scale,0,0,7);ctx.fill();if(o.light){const g=ctx.createRadialGradient(0,0,4,0,0,52);g.addColorStop(0,'#e6d49e32');g.addColorStop(1,'#e6d49e00');ctx.fillStyle=g;ctx.beginPath();ctx.arc(0,0,52,0,7);ctx.fill();}ctx.restore();}
 }
 let floorCache;
 function buildFloorCache(){const saved={W,H,ctx,cam:state.cam,zoom:state.zoom},points=level.shapes.flat().map(([x,y])=>[(x-y)*38,(x+y)*19]);const left=Math.floor(Math.min(...points.map(p=>p[0])))-3,top=Math.floor(Math.min(...points.map(p=>p[1])))-3,right=Math.ceil(Math.max(...points.map(p=>p[0])))+3,bottom=Math.ceil(Math.max(...points.map(p=>p[1])))+3;const c=document.createElement('canvas');c.width=right-left;c.height=bottom-top;ctx=c.getContext('2d');ctx.imageSmoothingEnabled=false;W=c.width;H=c.height;const diff=(W/2+left)/38,sum=(H*.53+top)/19;state.cam={x:(sum+diff)/2,y:(sum-diff)/2};state.zoom=1;
  ctx.save();ctx.beginPath();for(const poly of level.shapes){poly.forEach((v,i)=>i?ctx.lineTo(...project(...v)):ctx.moveTo(...project(...v)));ctx.closePath();}ctx.clip();
  for(let y=0;y<level.h;y++)for(let x=0;x<level.w;x++){if(!level.shapes.some(poly=>inside(x+.5,y+.5,poly)||inside(x+.01,y+.01,poly)||inside(x+.99,y+.99,poly)||inside(x+.99,y+.01,poly)||inside(x+.01,y+.99,poly)))continue;const v=tileVertices(x,y);polygon(v,'#59665e');textureQuad(surfaceTextures.floor,v);polygon(v,null,'#34463d8a');}floorAccents();ctx.restore();floorCache={canvas:c,left,top};W=saved.W;H=saved.H;ctx=saved.ctx;state.cam=saved.cam;state.zoom=saved.zoom;}
 function cachedFloor(){const p=project(0,0),z=state.zoom;ctx.drawImage(floorCache.canvas,Math.round(p[0]+floorCache.left*z),Math.round(p[1]+floorCache.top*z),Math.round(floorCache.canvas.width*z),Math.round(floorCache.canvas.height*z));}
 function planterDraw(o){const a={x:o.x-.3,y:o.y+.3,ux:1,uy:0},b={x:o.x+.3,y:o.y-.3,ux:0,uy:1,axis:'y'};textureQuad(surfaceTextures.wall,wallFace(a,0,.6,0,.34));textureQuad(surfaceTextures.wall,wallFace(b,0,.6,0,.34));polygon([[o.x-.3,o.y-.3,.34],[o.x+.3,o.y-.3,.34],[o.x+.3,o.y+.3,.34],[o.x-.3,o.y+.3,.34]],'#555b3e','#8c8d6f');}
 // Stairs are assembled from the very same floor/grate/wall sprite faces and baked once.
 const stairCaches={};
 function rawStairs(o){const isA=o.id==='stairA',x=isA?3:17,y=isA?15:0,w=isA?4:6,h=isA?6:4;polygon([[x,y,0],[x+w,y,0],[x+w,y+h,0],[x,y+h,0]],'#0d1915','#7f8775');for(let i=0;i<8;i++){const dep=(8-i)*.14;if(isA){const xx=x+i*.5;textureQuad(surfaceTextures.grate,[[xx,y,-dep],[xx+.5,y,-dep],[xx+.5,y+h,-dep],[xx,y+h,-dep]]);textureQuad(surfaceTextures.wall,[[xx+.5,y,-dep+.14],[xx+.5,y+h,-dep+.14],[xx+.5,y+h,-dep],[xx+.5,y,-dep]]);}else{const yy=y+i*.5;textureQuad(surfaceTextures.grate,[[x,yy,-dep],[x+w,yy,-dep],[x+w,yy+.5,-dep],[x,yy+.5,-dep]]);textureQuad(surfaceTextures.wall,[[x,yy+.5,-dep+.14],[x+w,yy+.5,-dep+.14],[x+w,yy+.5,-dep],[x,yy+.5,-dep]]);}}}
 function stairsDraw(o){const a=o.id==='stairA',x=a?3:17,y=a?15:0,w=a?4:6,h=a?6:4;ctx.save();ctx.beginPath();[[x,y],[x+w,y],[x+w,y+h],[x,y+h]].forEach((v,i)=>i?ctx.lineTo(...project(...v)):ctx.moveTo(...project(...v)));ctx.closePath();ctx.clip();rawStairs(o);ctx.restore();polygon([[x,y,0],[x+w,y,0],[x+w,y+h,0],[x,y+h,0]],null,'#798574');}

 // Four hand-authored sprite directions are selected from the projected movement vector.
 // Rows: north-east, south-east, south-west, north-west. Source pivot: (32, 80).
 function actorDirection(dx,dy){const sx=dx-dy,sy=dx+dy;return sx>=0?(sy>=0?1:0):(sy>=0?2:3);}
 function actor(){
  const f=player.moving?Math.floor(player.phase/(Math.PI*2)*8)%8:8,p=project(player.x,player.y),z=state.zoom,scale=1.2*z;
  ctx.fillStyle='#08110e45';ctx.beginPath();ctx.ellipse(p[0],p[1],12*z,5*z,0,0,7);ctx.fill();
  ctx.strokeStyle='#b7ac78';ctx.lineWidth=Math.max(1,z);ctx.beginPath();ctx.ellipse(p[0],p[1],13*z,5*z,0,0,7);ctx.stroke();
  ctx.drawImage(images.resident,f*64,player.facing*88,64,88,Math.round(p[0]-32*scale),Math.round(p[1]-80*scale),Math.round(64*scale),Math.round(88*scale));
 }
 function steam(){const cycle=state.cycle;if(!cycle||cycle.phase!=='steam')return;const b=level.chambers[cycle.lane],strength=Math.min(1,cycle.t/.8,(4.8-cycle.t)/.6);for(let i=0;i<65;i++){const t=(time*.35+i*.037)%1,x=b.x+.25+(i*1.73%(b.w-.5)),y=b.y+.2+(i*2.11%(b.h-.4)),p=project(x,y,t*2.3),r=(3+t*8)*state.zoom;ctx.fillStyle=`rgba(201,218,204,${Math.max(0,strength*(1-t)*.17)})`;ctx.fillRect(Math.round(p[0]-r),Math.round(p[1]-r*.65),Math.ceil(r*2),Math.ceil(r*1.3));}}
 function render(){if(!ready||!running)return;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.imageSmoothingEnabled=false;ctx.fillStyle='#131a16';ctx.fillRect(0,0,W,H);cachedFloor();for(const o of level.objects.filter(o=>o.kind==='stairs'))stairsDraw(o);
  if(state.path.length){ctx.strokeStyle='#c2bc8180';ctx.lineWidth=1;ctx.setLineDash([3,5]);ctx.beginPath();ctx.moveTo(...project(player.x,player.y,.02));for(const p of state.path)ctx.lineTo(...project(p.x,p.y,.02));ctx.stroke();ctx.setLineDash([]);}
  const draws=[...level.walls.map(o=>({...o,kind:'wall'})),...level.objects.filter(o=>!['stairs','floorMarker','fixture'].includes(o.kind)),...level.doors,{kind:'actor',depth:player.x+player.y+.02}].sort((a,b)=>a.depth-b.depth);
  for(const o of draws){const p=project(o.x??player.x,o.y??player.y);if(o.kind!=='actor'&&(p[0]<-250||p[0]>W+250||p[1]<-60||p[1]>H+200))continue;if(o.kind==='wall')wallDraw(o);else if(o.kind==='door')doorDraw(o);else if(o.kind==='fixture')fixtureDraw(o);else if(o.kind==='actor')actor();else if(o.action==='container'&&CONTAINER_SPRITES.includes(o.sprite))containerDraw(o);else{if(o.planter)planterDraw(o);drawSprite(o.sprite,o.x,o.y,o.scale,.5,o.flip,o.planter?.3:o.z||0,o.foot||1);}}
  steam();
  for(const o of interactables()){const p=o.door?project(...doorWorld(o,.5,1.5)):project(o.x,o.y,o.z??(o.kind==='floorMarker'?.08:1.3));if(p[0]<0||p[0]>W||p[1]<0||p[1]>H)continue;const near=state.near?.id===o.id;ctx.fillStyle=near?'#dfca86':'#9bac8a';ctx.fillRect(Math.round(p[0]-2),Math.round(p[1]-2),4,4);if(state.selected?.id===o.id||near){ctx.strokeStyle='#dbc988';ctx.strokeRect(Math.round(p[0]-5),Math.round(p[1]-5),10,10);}}
  dirty=false;
 }
 function resize(){W=Math.max(280,canvas.clientWidth||window.innerWidth);H=Math.max(240,canvas.clientHeight||window.innerHeight);dpr=Math.min(window.devicePixelRatio||1,3);canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr);dirty=true;if(running)render();}
 function followPlayer(dt){if(!state.follow||!player.moving)return;const p=project(player.x,player.y),dx=p[0]-W*.5,dy=p[1]-H*.51,mx=W*.17,my=H*.13;const ox=Math.abs(dx)>mx?dx-Math.sign(dx)*mx:0,oy=Math.abs(dy)>my?dy-Math.sign(dy)*my:0;if(ox||oy){const t=Math.min(1,dt*6);state.cam.x+=(ox/(38*state.zoom)+oy/(19*state.zoom))/2*t;state.cam.y+=(oy/(19*state.zoom)-ox/(38*state.zoom))/2*t;dirty=true;}}
 function frame(now){requestAnimationFrame(frame);const dt=Math.min(.04,(now-last)/1000||.016);last=now;if(!ready||!running||paused||document.hidden)return;time+=dt;let dx=0,dy=0;const sx=(keys.has('ArrowRight')||keys.has('KeyD')?1:0)-(keys.has('ArrowLeft')||keys.has('KeyA')?1:0),sy=(keys.has('ArrowDown')||keys.has('KeyS')?1:0)-(keys.has('ArrowUp')||keys.has('KeyW')?1:0);if(!state.cycle&&!state.container){if(sx||sy){state.path=[];state.selected=null;state.goal=null;dx=sx+sy;dy=sy-sx;}else if(state.path.length){const p=state.path[0];dx=p.x-player.x;dy=p.y-player.y;if(Math.hypot(dx,dy)<.035){player.x=p.x;player.y=p.y;state.path.shift();dx=dy=0;}}}const was=player.moving;player.moving=move(dx,dy,dt);if(player.moving||was)dirty=true;if((dx||dy)&&!player.moving){state.path=[];say('Проход закрыт. Выберите дверь или свободный пол.');}animate(dt);followPlayer(dt);updateAction();if(dirty)render();}
 function clickScene(x,y){if(paused||state.cycle||state.container)return;let best=null,dist=32;for(const o of interactables()){const p=o.door?project(...doorWorld(o,.5,1.1)):project(o.x,o.y,o.z??(o.kind==='floorMarker'?.05:.65)),d=Math.hypot(x-p[0],y-p[1]);if(d<dist){best=o;dist=d;}}if(best){request(best);return;}const p=inverse(x,y),route=pathTo(p.x,p.y);state.goal=null;if(route){state.path=route;state.selected=null;say('');}else say('Проход закрыт. Нажмите на дверь или свободный пол.');dirty=true;}
 canvas.addEventListener('pointerdown',e=>{if(paused||!running||!e.isPrimary)return;pointer={id:e.pointerId,x:e.clientX,y:e.clientY,cam:{...state.cam},drag:false};canvas.setPointerCapture(e.pointerId);});
 canvas.addEventListener('pointermove',e=>{if(!pointer||pointer.id!==e.pointerId)return;const dx=e.clientX-pointer.x,dy=e.clientY-pointer.y;if(Math.hypot(dx,dy)>8)pointer.drag=true;if(pointer.drag){state.follow=false;state.cam.x=pointer.cam.x-(dx/(38*state.zoom)+dy/(19*state.zoom))/2;state.cam.y=pointer.cam.y-(dy/(19*state.zoom)-dx/(38*state.zoom))/2;dirty=true;}});
 canvas.addEventListener('pointerup',e=>{if(!pointer||pointer.id!==e.pointerId)return;const p=pointer;pointer=null;if(!p.drag){const b=canvas.getBoundingClientRect();clickScene(e.clientX-b.left,e.clientY-b.top);}});canvas.addEventListener('pointercancel',()=>pointer=null);
 canvas.addEventListener('wheel',e=>{if(!running||paused)return;e.preventDefault();zoom(e.deltaY<0?.125:-.125);},{passive:false});
 for(const[id,code]of[['move-left','ArrowLeft'],['move-right','ArrowRight'],['move-up','ArrowUp'],['move-down','ArrowDown']]){const b=document.getElementById(id);b.addEventListener('pointerdown',e=>{if(paused||!running)return;keys.add(code);b.setPointerCapture(e.pointerId);e.preventDefault();});for(const ev of['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,()=>keys.delete(code));}
 document.addEventListener('keydown',e=>{if(!running||paused||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyW','KeyA','KeyS','KeyD'].includes(e.code)){e.preventDefault();keys.add(e.code);}if(e.code==='KeyE'&&!e.repeat)act();});document.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{keys.clear();pointer=null;});document.addEventListener('visibilitychange',()=>keys.clear());
 function zoom(delta){state.zoom=Math.max(.25,Math.min(2,state.zoom+delta));dirty=true;}
 function fitArea(points,max=1){const p=points.map(([x,y])=>[(x-y)*38,(x+y)*19]),minX=Math.min(...p.map(a=>a[0])),maxX=Math.max(...p.map(a=>a[0])),minY=Math.min(...p.map(a=>a[1]))-110,maxY=Math.max(...p.map(a=>a[1]));state.zoom=Math.max(.2,Math.min(max,(W-100)/(maxX-minX),(H-155)/(maxY-minY)));const a=(minX+maxX)/2/38,b=(minY+maxY)/2/19;state.cam={x:(a+b)/2,y:(b-a)/2};state.follow=false;dirty=true;}
 function overview(){fitArea(level.shapes.flat());}
 function foyerView(){fitArea(level.hall,1);}
 function renderPlan(c){const w=c.clientWidth||600,h=c.clientHeight||330,r=Math.min(window.devicePixelRatio||1,3),g=c.getContext('2d');c.width=w*r;c.height=h*r;g.setTransform(r,0,0,r,0,0);g.fillStyle='#0b1710';g.fillRect(0,0,w,h);const scale=Math.min((w-60)/44,(h-35)/49),ox=(w-44*scale)/2,oy=15,p=(x,y)=>[ox+x*scale,oy+y*scale];g.fillStyle='#1c3825';g.strokeStyle='#66895b';g.lineWidth=1.2;for(const poly of level.shapes){g.beginPath();poly.forEach((a,i)=>i?g.lineTo(...p(...a)):g.moveTo(...p(...a)));g.closePath();g.fill();g.stroke();}g.strokeStyle='#a69561';g.beginPath();g.arc(...p(20,19),3*scale,0,7);g.stroke();for(const d of level.doors){g.strokeStyle=doorClear(d)?'#8ebc73':'#c08458';g.beginPath();g.moveTo(...p(d.x,d.y));g.lineTo(...p(d.x+d.ux*d.span,d.y+d.uy*d.span));g.stroke();}g.font='bold 11px monospace';g.textAlign='center';g.textBaseline='middle';for(const[t,x,y]of[['1',18.5,12],['2',24,10],['3',13.5,24],['4',17,25],['5',11.5,14.5],['6',20,39],['7',39,19],['8',5,18]]){const [px,py]=p(x,y);g.fillStyle='#102519';g.strokeStyle='#b4ad78';g.beginPath();g.arc(px,py,9,0,7);g.fill();g.stroke();g.fillStyle='#e0d5a4';g.fillText(t,px,py+.5);}g.fillStyle='#e7c97d';g.beginPath();g.arc(...p(player.x,player.y),4,0,7);g.fill();}
 async function init(){const names=[...new Set([...CONTAINER_SPRITES.map(name=>name+'Opening'),'resident','wallA','wallB','wallDetailA','floor','grate','door','boxOpen',...level.objects.map(o=>o.sprite).filter(Boolean)])];await Promise.all(names.map(async name=>{const im=new Image();im.src='assets/'+name+'-cut.png';await new Promise((ok,no)=>{im.onload=ok;im.onerror=()=>no(new Error('Не загрузился '+name));if(im.complete&&im.naturalWidth)ok();});images[name]=im;const c=document.createElement('canvas');c.width=im.width;c.height=im.height;const g=c.getContext('2d');g.drawImage(im,0,0);g.globalCompositeOperation='source-atop';g.fillStyle='rgba(12,25,24,.49)';g.fillRect(0,0,c.width,c.height);darkImages[name]=c;}));buildSurfaces();buildFloorCache();ready=true;requestAnimationFrame(frame);}
 let started=false;
 const api={onSound:null,onAction:null,onPass:null,requestPass,confirmClass,getPass,onNotice:null,onTarget:null,onScene:null,onProcess:null,start(){running=true;paused=false;resize();if(!started){started=true;state.cam={x:20.5,y:43.5};state.zoom=H<520?.9:1.1;}updateAction();dirty=true;},pause(v){paused=v;keys.clear();pointer=null;player.moving=false;dirty=true;},stop(){running=false;keys.clear();},center(){state.cam={x:player.x,y:player.y};state.follow=true;if(state.zoom<.75)state.zoom=1;dirty=true;},overview,foyerView,zoom,act,closeContainer,renderPlan,getScene(){return state.scene;},route(id){const obj=interactables().find(o=>o.id===id);if(obj)request(obj);},isBusy(){return !!state.cycle||containerBusy();}};
 new ResizeObserver(resize).observe(canvas);api.ready=init();return api;
})();
